# Generated by Django 3.2.7 on 2021-09-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupo',
            table='Grupo',
        ),
    ]
