# Generated by Django 3.2.7 on 2021-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_alter_grupo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descricao',
            field=models.CharField(max_length=110, unique=True, verbose_name='Descrição'),
        ),
    ]
