# Generated by Django 3.2.7 on 2021-10-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisoes', '0002_alter_divisao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='codigo',
            field=models.CharField(max_length=1, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='descricao',
            field=models.CharField(max_length=80, unique=True, verbose_name='Descrição'),
        ),
    ]
