# Generated by Django 3.2.7 on 2021-10-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacaolicenciamento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivo', verbose_name='Arquivo'),
        ),
    ]
