# Generated by Django 3.2.7 on 2021-10-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciamentos', '0002_alter_documentacaolicenciamento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacaolicenciamento',
            name='status',
            field=models.CharField(default='Enviado', max_length=20, verbose_name='Status'),
        ),
    ]
