# Generated by Django 3.2.7 on 2021-09-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0002_alter_grupo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'SubGrupo',
                'verbose_name_plural': 'SubGrupos',
                'db_table': 'Subgrupo',
                'ordering': ['grupo'],
            },
        ),
    ]
