# Generated by Django 3.2.7 on 2021-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrupo',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subgrupo',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
