# Generated by Django 3.2.7 on 2021-09-27 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subgrupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('und_medida_desc', models.CharField(max_length=255, verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'Unidade_medida',
                'ordering': ['und_medida_desc'],
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('p_poluidor', models.CharField(max_length=1, verbose_name='Potencial Poluidor')),
                ('descricao', models.CharField(max_length=100)),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgrupos.subgrupo', verbose_name='SubGrupo')),
                ('und_medida_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipologias.unidade_medida', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologias',
                'db_table': 'Tipologia',
                'ordering': ['subgrupo'],
            },
        ),
    ]
