# Generated by Django 3.2.7 on 2021-10-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subgrupos', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgrupos.subgrupo', verbose_name='Código e Descrição do SubGrupo'),
        ),
    ]
