# Generated by Django 3.2.7 on 2021-10-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subgrupos', '0001_initial'),
        ('tipologias', '0002_auto_20211003_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgrupos.subgrupo', verbose_name='SubGrupo'),
        ),
    ]
