# Generated by Django 3.2.7 on 2021-10-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0003_alter_tipologia_subgrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='p_poluidor',
            field=models.CharField(choices=[('A', 'A'), ('M', 'M'), ('P', 'P')], max_length=1, verbose_name='Potencial Poluidor'),
        ),
    ]
