# Generated by Django 3.2.7 on 2021-10-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0006_auto_20211003_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='p_poluidor',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('M', 'M'), ('P', 'P')], max_length=1, null=True, verbose_name='Potencial Poluidor'),
        ),
    ]
