# Generated by Django 3.2.7 on 2021-10-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0007_alter_tipologia_p_poluidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tipologias/pdfs/'),
        ),
    ]
