# Generated by Django 3.2.7 on 2021-10-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0008_tipologia_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='pdf',
            field=models.FileField(default='', upload_to='tipologias/pdfs/'),
            preserve_default=False,
        ),
    ]
