# Generated by Django 3.2.7 on 2021-10-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0011_alter_tipologia_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='pdf',
            field=models.FileField(upload_to='tipologias/pdfs/', verbose_name='PDF'),
        ),
    ]
